### ISSUE TITLE
Offer GDMUT as a NuGet package

### ISSUE THREAD

**Issue by mk56-spn** [Spycemyster/GDMUT#1]
This is more of a feature request, really neat little unit tester youve made here!, just figured that being able to install with nuget would be nice due to it adding less files to the project and overall being a cleaner integration with c#

that is all and thanks for making this

**Comment by Spycemyster** [comment]
Thanks for using the tool, I'm glad people are liking it!

I'm not sure about the viability as a Nuget package. Godot requires their plugins to be downloaded in a specific way since they have to be in the "addons" folder within a project structure. And IIRC, Nuget packages must be library references or a CLI tool.
